Repository abhishekpatelmc/QuestBook, pull requests merged in 2023-03, with the labels that each got.

#10 Fix: Added country view and urls
  home/urls.py
  home/views.py
Labels: enhancement

#12 Fix: view and URL
  home/urls.py
  home/views.py
Labels: duplicate, enhancement

#13 Dev hetvi
  home/templates/home/adventure_details.html
  home/templates/home/index.html
  home/urls.py
  home/views.py
Labels: enhancement

#14 Fix: Country page and country details page with adventues working -- …
  home/templates/home/country_details.html
  home/templates/home/index.html
  home/views.py
  media/images/India_KjZ1gAZ.jpeg
  media/images/India_SGyY5Be.jpeg
Labels: bug, enhancement

#15 Fix: All the navigation working -- Except booking form added about page
  home/templates/home/about.html
  home/templates/home/adventure_details.html
  home/templates/home/country_details.html
  home/templates/home/index.html
  home/urls.py
  home/views.py
Labels: bug, enhancement

#16 Fix: all the destinations are navgating fine now
  home/templates/home/adventure_details.html
  home/templates/home/index.html
  home/urls.py
  home/views.py
  media/images/India.jpeg
  media/images/India_KjZ1gAZ.jpeg
  media/images/India_PAZPP6t.jpeg
  media/images/India_SGyY5Be.jpeg
  media/images/canada.jpg
  media/images/canada_mVzb2y8.jpg
  media/images/niagarafalls.jpg
Labels: bug

#17 Fix: modified gitignore
  .gitignore
  media/images/India.jpeg
  media/images/treck_IvaqPOM.jpg
Labels: bug

#19 Fix: country details name added
  home/templates/home/country_details.html
  home/views.py
Labels: documentation

#20 Fix: Adventures displaying on index page
  home/templates/home/index.html
  home/views.py
Labels: documentation, enhancement

#22 Fix: Modified models
  home/forms.py
  home/migrations/0002_pessanger_detail.py
  home/models.py
  home/templates/home/booking.html
  home/templates/home/index.html
  home/templates/home/payment.html
  home/urls.py
  home/views.py
Labels: enhancement

#23 Fix: About redirect
  Resource/Adventures
  Resource/Adventures.json
  Resource/Countries
  Resource/Countries.json
  home/templates/home/booking.html
  home/urls.py
  home/views.py
Labels: bug, enhancement

#26 Fix: Recent UI changes added and fixed conflicts
  .idea/QuestBook.iml
  .idea/dataSources.xml
  .idea/misc.xml
  home/forms.py
  home/models.py
  home/templates/home/booking.html
  home/templates/home/login.html
  home/urls.py
  home/views.py
Labels: bug, enhancement

#34 Dev abhishek
  home/templates/home/adventure_details.html
  home/templates/home/country_details.html
  home/templates/home/index.html
  home/views.py
  media/images/India1_HrIa8yZ.jpg
  media/images/India1_I28EkGd.jpg
  media/images/aaron-sebastian-bfgEYpS0Znk-unsplash.jpg
  media/images/aaron-sebastian-bfgEYpS0Znk-unsplash_Jr3htVB.jpg
  media/images/boxed-water-is-better-5Lw1U5BIumE-unsplash.jpg
  media/images/boxed-water-is-better-5Lw1U5BIumE-unsplash_63gVLN1.jpg
  media/images/india2_4y4B0x0.jpg
  media/images/india2_KJxQ5yu.jpg
  media/images/nico-amatullo-2L1QbZglOCE-unsplash_TiyaPBU.jpg
  media/images/usa1.jpg
  media/images/usa2.jpg
  media/images/usa2_QWYFRCa.jpg
  media/images/usa3.jpg
  media/images/usa3_OU3DbY7.jpg
  media/images/usa5.jpg
  media/images/zahid-lilani-sJb3qEwgFn4-unsplash_xPrf68K.jpg
Labels: bug, enhancement
